### ISSUE TITLE
redis5如何实现本地缓存自动失效呢

### ISSUE THREAD

**Issue by BearstOzawa** [qy8502/jetcache-plus#1]

**Comment by qy8502** [comment]
那实现起来就很麻烦了，相当于所有写缓存的操作你都要知道并管起来，然后通知其他节点失效。实现成本太高了，比不上redis6 新特性带来的便利。生产环境如果自己能做主，还是建议升级到redis6吧。

**Comment by gundamff** [comment]
监听key的变更事件(Keyspace Notifications), 然后根据事件做响应的处理, 可行但还是很麻烦就是了

**Comment by BearstOzawa** [comment]
> 监听key的变更事件(Keyspace Notifications), 然后根据事件做响应的处理, 可行但还是很麻烦就是了
> 那实现起来就很麻烦了，相当于所有写缓存的操作你都要知道并管起来，然后通知其他节点失效。实现成本太高了，比不上redis6 新特性带来的便利。生产环境如果自己能做主，还是建议升级到redis6吧。

现在做的一种方案：缓存变更之后，利用redis自带的pub\sub通知其他服务清除缓存。这样做不知道在性能上会有没有障碍
